name: RPGDeath
main: me.bumblebeee_.rpgdeath.RPGDeath
version: 1.0-SNAPSHOT
author: [BumbleBee]
depend: [Vault, WorldGuard]
description: Desc
commands:
  morto:
    description: Kill a player
  resuscita:
    description: Revive a player
  trovaanima:
    description: Give compass targeting a player
  death:
    description: Reloads the plugin

permissions:
  death.death:
    description: Death effects
    default: false
  death.invincibility:
    description: invincibility
    default: false